const filtersHealth = {
  ACUTE_CHRONIC: 'ACUTE_COND',
  DENTIST: 'DENTIST',
  ORT: 'ORT',
  EMERGENCY: 'EMERGENCY',
  GBV: 'GBV',
  MALNUTRITION: 'MALNUTRITI',
  PSYCHOTHERAPY: 'PSYCHOTHER',
  PHYSIOTHERAPY: 'PHYSIOTHER',
  REPRODUCTIVE: 'REPRODUCTI',
  SECONDARY: 'SECONDARY',
  VACCINATION: 'VACCINATIO',
};

export default filtersHealth;
